# Generated by Django 4.1.1 on 2022-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingarea', models.CharField(max_length=27)),
                ('camperimage1', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingsite', models.CharField(max_length=27)),
                ('campingprefecture', models.CharField(max_length=27)),
                ('campeinginfo', models.TextField(blank=True, max_length=155)),
                ('camperimage2', models.ImageField(blank=True, upload_to='images/campingsites')),
            ],
        ),
    ]
