# Generated by Django 4.1.1 on 2022-09-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingtit1', models.CharField(blank=True, max_length=27)),
                ('campingarea', models.CharField(blank=True, max_length=27)),
                ('camperimage1', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingsite', models.CharField(blank=True, max_length=27)),
                ('campingprefecture', models.CharField(blank=True, max_length=27)),
                ('campeinginfo', models.TextField(blank=True, max_length=155)),
                ('camperimage2', models.ImageField(blank=True, upload_to='images/campingsites')),
            ],
            options={
                'verbose_name': 'campingsites',
                'verbose_name_plural': 'Camping Sites',
            },
        ),
        migrations.CreateModel(
            name='CampingSitejpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingtit1', models.CharField(blank=True, max_length=27)),
                ('campingarea', models.CharField(blank=True, max_length=27)),
                ('camperimage1', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingsite', models.CharField(blank=True, max_length=27)),
                ('campingprefecture', models.CharField(blank=True, max_length=27)),
                ('campeinginfo', models.TextField(blank=True, max_length=155)),
                ('camperimage2', models.ImageField(blank=True, upload_to='images/campingsites')),
            ],
            options={
                'verbose_name': 'campingsites',
                'verbose_name_plural': 'Camping Sites',
            },
        ),
        migrations.DeleteModel(
            name='CampingSites',
        ),
    ]
