# Generated by Django 4.1.1 on 2022-09-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campercontact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookAnthonyCamper',
            new_name='AmityCamperInquiry',
        ),
        migrations.RenameModel(
            old_name='BookAmityCamper',
            new_name='AnthonyCamperInquiry',
        ),
    ]
