# Generated by Django 4.1.1 on 2022-09-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campercontact', '0002_rename_bookanthonycamper_amitycamperinquiry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amitycamperinquiry',
            options={'verbose_name': 'camperinquiry1', 'verbose_name_plural': 'Amity Camper Inquiry'},
        ),
        migrations.AlterModelOptions(
            name='anthonycamperinquiry',
            options={'verbose_name': 'camperinquiry2', 'verbose_name_plural': 'Anthony Camper Inquiry'},
        ),
    ]
