# Generated by Django 4.1.1 on 2022-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campername', models.CharField(choices=[('AMITY', 'Amity Camper'), ('ANTHONY', 'Anthony Camper')], max_length=7)),
                ('camperinfo', models.TextField(blank=True, max_length=155)),
                ('maker', models.CharField(max_length=25)),
                ('transmission', models.CharField(max_length=25)),
                ('wheeldrive', models.CharField(max_length=25)),
                ('passenger', models.IntegerField()),
                ('camperimage', models.ImageField(blank=True, upload_to='images/camperinfo')),
            ],
            options={
                'verbose_name': 'camperinfo',
                'verbose_name_plural': 'Camper Info',
            },
        ),
        migrations.CreateModel(
            name='Camperjpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campername', models.CharField(choices=[('AMITY', 'Amity Camper'), ('ANTHONY', 'Anthony Camper')], max_length=7)),
                ('camperinfo', models.TextField(blank=True, max_length=155)),
                ('maker', models.CharField(max_length=25)),
                ('transmission', models.CharField(max_length=25)),
                ('wheeldrive', models.CharField(max_length=25)),
                ('passenger', models.IntegerField()),
                ('camperimage', models.ImageField(blank=True, upload_to='images/camperinfo')),
            ],
            options={
                'verbose_name': 'camperinfojpn',
                'verbose_name_plural': 'Camper Info Jpn',
            },
        ),
    ]
