# Generated by Django 4.1.1 on 2022-09-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camper',
            options={'verbose_name': 'camper', 'verbose_name_plural': 'Camper '},
        ),
        migrations.AlterModelOptions(
            name='camperjpn',
            options={'verbose_name': 'camperjpn', 'verbose_name_plural': 'Camper Jpn'},
        ),
    ]
