# Generated by Django 4.1.1 on 2022-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0003_camper_camperinfo2_camper_camperprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='petsok',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='camperjpn',
            name='petsok',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
