# Generated by Django 4.1.1 on 2022-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0004_camper_petsok_camperjpn_petsok'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='carnavi',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='camperjpn',
            name='carnavi',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
