# Generated by Django 4.1.1 on 2022-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0007_camperaboutjpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperabout',
            name='content1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='content2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='content4',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='tit1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='tit2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='tit3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='camperabout',
            name='tit4',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
