# Generated by Django 4.1.1 on 2022-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0008_alter_camperabout_content1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperabout',
            name='content3',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
