# Generated by Django 4.1.1 on 2022-09-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0010_alter_camperabout_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingtit1', models.CharField(blank=True, max_length=27)),
                ('campinginfo1', models.CharField(blank=True, max_length=27)),
                ('camperimage1', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingtit2', models.CharField(blank=True, max_length=27)),
                ('campinginfo2', models.CharField(blank=True, max_length=27)),
                ('camperimage2', models.ImageField(blank=True, upload_to='images/campingsites')),
            ],
            options={
                'verbose_name': 'campingsites',
                'verbose_name_plural': 'Camping Site Info',
            },
        ),
    ]
