# Generated by Django 4.1.1 on 2022-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0011_campingsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='campingsite',
            name='camperimage3',
            field=models.ImageField(blank=True, upload_to='images/campingsites'),
        ),
        migrations.AddField(
            model_name='campingsite',
            name='campinginfo3',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AddField(
            model_name='campingsite',
            name='campingtit3',
            field=models.CharField(blank=True, max_length=27),
        ),
    ]
