# Generated by Django 4.1.1 on 2022-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0012_campingsite_camperimage3_campingsite_campinginfo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingsite',
            name='campinginfo1',
            field=models.CharField(blank=True, max_length=77),
        ),
        migrations.AlterField(
            model_name='campingsite',
            name='campinginfo2',
            field=models.CharField(blank=True, max_length=77),
        ),
        migrations.AlterField(
            model_name='campingsite',
            name='campinginfo3',
            field=models.CharField(blank=True, max_length=77),
        ),
    ]
