# Generated by Django 4.1.1 on 2022-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0013_alter_campingsite_campinginfo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSitejpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingtit1', models.CharField(blank=True, max_length=27)),
                ('campinginfo1', models.CharField(blank=True, max_length=77)),
                ('camperimage1', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingtit2', models.CharField(blank=True, max_length=27)),
                ('campinginfo2', models.CharField(blank=True, max_length=77)),
                ('camperimage2', models.ImageField(blank=True, upload_to='images/campingsites')),
                ('campingtit3', models.CharField(blank=True, max_length=27)),
                ('campinginfo3', models.CharField(blank=True, max_length=77)),
                ('camperimage3', models.ImageField(blank=True, upload_to='images/campingsites')),
            ],
            options={
                'verbose_name': 'campingsitesjpn',
                'verbose_name_plural': 'Camping Site Info jpn',
            },
        ),
    ]
