# Generated by Django 4.1.1 on 2022-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0014_campingsitejpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperabout',
            name='maindesc',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camperaboutjpn',
            name='maindesc',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
