# Generated by Django 4.1.1 on 2022-10-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0015_camperabout_maindesc_camperaboutjpn_maindesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperabout',
            name='maindesc',
            field=models.TextField(blank=True, max_length=777),
        ),
        migrations.AlterField(
            model_name='camperaboutjpn',
            name='maindesc',
            field=models.TextField(blank=True, max_length=777),
        ),
    ]
