# Generated by Django 4.1.1 on 2022-09-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camperinfo', '0002_alter_camper_options_alter_camperjpn_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camperbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateTimeField()),
                ('dropoff', models.DateTimeField()),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camperinfo.camper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
