# Generated by Django 4.1.1 on 2022-09-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camperinfo', '0005_camper_carnavi_camperjpn_carnavi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camperbooking', '0003_rename_camperavailability_camperbooking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camperbooking',
            options={'verbose_name': 'camperbooking', 'verbose_name_plural': 'Camper Booking Amity'},
        ),
        migrations.CreateModel(
            name='CamperBooking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateTimeField()),
                ('dropoff', models.DateTimeField()),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camperinfo.camper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'camperbooking',
                'verbose_name_plural': 'Camper Booking Amity',
            },
        ),
    ]
