# Generated by Django 4.1.1 on 2022-09-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperbooking', '0004_alter_camperbooking_options_camperbooking2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camperbooking2',
            options={'verbose_name': 'camperbooking', 'verbose_name_plural': 'Camper Booking Anthony'},
        ),
        migrations.AddField(
            model_name='camperbooking',
            name='bookername',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AddField(
            model_name='camperbooking2',
            name='bookername',
            field=models.CharField(blank=True, max_length=27),
        ),
    ]
