# Generated by Django 4.1.1 on 2022-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camperbooking', '0006_remove_camperbooking_bookername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperbooking',
            name='booker',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AddField(
            model_name='camperbooking2',
            name='booker',
            field=models.CharField(blank=True, max_length=27),
        ),
    ]
